### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by PranavMasekar** [nsccpccoe/nscc-app#3]
Add brief introduction about NSCC Moible Application

**Comment by Rishav1707** [comment]
Give me a brief introduction about NSCC and what it is for @PranavMasekar

**Comment by PranavMasekar** [comment]
This application is for Newton School Coding Club , PCCOE and it only interest our institute.

**Comment by Rishav1707** [comment]
Any image?
About Newton School Coding Club?
Purpose of this club? @PranavMasekar

**Comment by KarteekAti** [comment]
Institute Logo - https://entc.pccoepune.com/images/pccoe-logo.png
Newton School - https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/zfvkuf2k98lacoqpqdiw

Purpose - To educate students about Development and Problem-Solving using Contests, Content, Workshops, and many more interactive activities. The main purpose of the Mobile Application is to get notified about our contests, job opportunities, and team hiring, reading informational content. 

Just add some general information about Coding Clubs. @Rishav1707

**Comment by Rishav1707** [comment]
> Institute Logo - https://entc.pccoepune.com/images/pccoe-logo.png Newton School - https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/zfvkuf2k98lacoqpqdiw
> 
> Purpose - To educate students about Development and Problem-Solving using Contests, Content, Workshops, and many more interactive activities. The main purpose of the Mobile Application is to get notified about our contests, job opportunities, and team hiring, reading informational content.
> 
> Just add some general information about Coding Clubs. @Rishav1707

Ok

**Comment by PranavMasekar** [comment]
@Rishav1707 are you working on this issue ?

**Comment by Rishav1707** [comment]
> @Rishav1707 are you working on this issue ?

Yaah, why?

**Comment by PranavMasekar** [comment]
Add comment /assign so that GitHub bot can assign this issue to you

**Comment by KarteekAti** [comment]
@Rishav1707 please assign yourself to this issue.
